name: angel
description: An easily-extensible web server framework in Dart.
homepage: https://github.com/angel-dart/angel
publish_to: none
environment:
  sdk: ">=1.19.0"
dependencies: 
  angel_common: ^1.0.0
  angel_migration: ^1.0.0-alpha
  angel_orm: ^1.0.0-alpha
  angel_serialize: ^1.0.0-alpha
dev_dependencies:
  angel_hot: ^1.0.0
  angel_migration_runner: ^1.0.0-alpha
  angel_orm_generator: ^1.0.0-alpha
  angel_serialize_generator: ^1.0.0-alpha
  angel_test: ^1.0.0
  build_runner: ^0.3.0
  test: ^0.12.0
dependency_overrides:
  angel_migration_runner:
    path: ../migration/angel_migration_runner